### ISSUE TITLE
bring gyaa.ga back plz

### ISSUE THREAD

**Issue by Getindor** [cobcorn/lol#2]
thx

**Comment by LandonPowell** [comment]
Yeah, all you have to do is transfer on 000webhost from oldusers to newusers. It's easy. I want gyaa.ga/y/ back.

**Comment by LandonPowell** [comment]
Actually just make it a very aesthetic imageboard tbh.

**Comment by cobcorn** [comment]
shit lol whats gyaa.ga/y/

**Comment by cobcorn** [comment]
i literally forgot that my website existed lol

**Comment by cobcorn** [comment]
fuxking fixed

**Comment by Getindor** [comment]
yay xd
